### ISSUE TITLE
v1.2 Set as Wallpaper doesn't work on Windows 10

### ISSUE THREAD

**Issue by Gitorhit** [soroushchehresa/unsplash-wallpapers#14]
I saw this issue mentioned before, but seems like it is still not working, using release 1.2, it just keeps loading.

**Comment by souvikpodder** [comment]
@soroushchehresa Any update on this issue? is there any work around? Or I am missing something?

**Comment by soroushchehresa** [comment]
This issue is related to the [Wallpaper](https://www.npmjs.com/package/wallpaper) package. Anyway I updated the package to the latest version and just released a new version ([v1.3.0](https://github.com/soroushchehresa/unsplash-wallpapers/releases/tag/v1.3.0)).

**Comment by Gitorhit** [comment]
@soroushchehresa thanks for taking a look, however after installed v1.3.0, the issue still not resolved.
